# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/elena/OneDrive/Desktop/facultate/an3/ssc/lab/mips_multicicluv2/mips_multicicluv2.cache/wt [current_project]
set_property parent.project_path C:/Users/elena/OneDrive/Desktop/facultate/an3/ssc/lab/mips_multicicluv2/mips_multicicluv2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/elena/OneDrive/Desktop/facultate/an3/ssc/lab/mips_multicicluv2/mips_multicicluv2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/elena/OneDrive/Desktop/facultate/an3/ssc/lab/mips_multicicluv2/mips_multicicluv2.srcs/sources_1/new/MicroSequencer.vhd
  C:/Users/elena/OneDrive/Desktop/facultate/an3/ssc/lab/mips_multicicluv2/mips_multicicluv2.srcs/sources_1/new/MicroProgram.vhd
  C:/Users/elena/OneDrive/Desktop/facultate/an3/ssc/lab/mips_multicicluv2/mips_multicicluv2.srcs/sources_1/new/bistD.vhd
  C:/Users/elena/OneDrive/Desktop/facultate/an3/ssc/lab/mips_multicicluv2/mips_multicicluv2.srcs/sources_1/new/HEX7TOSEG.vhd
  C:/Users/elena/OneDrive/Desktop/facultate/an3/ssc/lab/mips_multicicluv2/mips_multicicluv2.srcs/sources_1/new/mux_srcpc.vhd
  C:/Users/elena/OneDrive/Desktop/facultate/an3/ssc/lab/mips_multicicluv2/mips_multicicluv2.srcs/sources_1/new/regALU.vhd
  C:/Users/elena/OneDrive/Desktop/facultate/an3/ssc/lab/mips_multicicluv2/mips_multicicluv2.srcs/sources_1/new/signext.vhd
  C:/Users/elena/OneDrive/Desktop/facultate/an3/ssc/lab/mips_multicicluv2/mips_multicicluv2.srcs/sources_1/new/RF.vhd
  C:/Users/elena/OneDrive/Desktop/facultate/an3/ssc/lab/mips_multicicluv2/mips_multicicluv2.srcs/sources_1/new/regPC.vhd
  C:/Users/elena/OneDrive/Desktop/facultate/an3/ssc/lab/mips_multicicluv2/mips_multicicluv2.srcs/sources_1/new/regB.vhd
  C:/Users/elena/OneDrive/Desktop/facultate/an3/ssc/lab/mips_multicicluv2/mips_multicicluv2.srcs/sources_1/new/regA.vhd
  C:/Users/elena/OneDrive/Desktop/facultate/an3/ssc/lab/mips_multicicluv2/mips_multicicluv2.srcs/sources_1/new/mux_wrdata.vhd
  C:/Users/elena/OneDrive/Desktop/facultate/an3/ssc/lab/mips_multicicluv2/mips_multicicluv2.srcs/sources_1/new/muxregdst.vhd
  C:/Users/elena/OneDrive/Desktop/facultate/an3/ssc/lab/mips_multicicluv2/mips_multicicluv2.srcs/sources_1/new/muxpc_mem.vhd
  C:/Users/elena/OneDrive/Desktop/facultate/an3/ssc/lab/mips_multicicluv2/mips_multicicluv2.srcs/sources_1/new/memDataReg.vhd
  C:/Users/elena/OneDrive/Desktop/facultate/an3/ssc/lab/mips_multicicluv2/mips_multicicluv2.srcs/sources_1/new/MEM.vhd
  C:/Users/elena/OneDrive/Desktop/facultate/an3/ssc/lab/mips_multicicluv2/mips_multicicluv2.srcs/sources_1/new/InstructionReg.vhd
  C:/Users/elena/OneDrive/Desktop/facultate/an3/ssc/lab/mips_multicicluv2/mips_multicicluv2.srcs/sources_1/new/EX.vhd
  C:/Users/elena/OneDrive/Desktop/facultate/an3/ssc/lab/mips_multicicluv2/mips_multicicluv2.srcs/sources_1/new/ControUnit.vhd
  C:/Users/elena/OneDrive/Desktop/facultate/an3/ssc/lab/mips_multicicluv2/mips_multicicluv2.srcs/sources_1/new/SSD.vhd
  C:/Users/elena/OneDrive/Desktop/facultate/an3/ssc/lab/mips_multicicluv2/mips_multicicluv2.srcs/sources_1/new/monoimpuls.vhd
  C:/Users/elena/OneDrive/Desktop/facultate/an3/ssc/lab/mips_multicicluv2/mips_multicicluv2.srcs/sources_1/new/mips_multi.vhd
  C:/Users/elena/OneDrive/Desktop/facultate/an3/ssc/lab/mips_multicicluv2/mips_multicicluv2.srcs/sources_1/new/top_env.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/elena/OneDrive/Desktop/facultate/an3/ssc/lab/mips_multicicluv2/mips_multicicluv2.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files C:/Users/elena/OneDrive/Desktop/facultate/an3/ssc/lab/mips_multicicluv2/mips_multicicluv2.srcs/constrs_1/new/constraints.xdc]


synth_design -top top_env -part xc7a35tcpg236-1


write_checkpoint -force -noxdef top_env.dcp

catch { report_utilization -file top_env_utilization_synth.rpt -pb top_env_utilization_synth.pb }
